### ISSUE TITLE
发现了bug

### ISSUE THREAD

**Issue by cnkerry** [smackgg/react-sku#1]
数据如下所示，看stocks最后一行数据，尺寸为 45，颜色分类为 5225黑色增高款 ，count是0，但是运行起来的时候，选择了尺寸 45，依然可以选择 5225黑色增高款
`attributes:[
      {
        "id": "20549",
        "title": "尺码",
        "childAttr": [
          {
            "id": "103189693",
            "title": "38"
          },
          {
            "id": "418624880",
            "title": "39"
          },
          {
            "id": "229418985",
            "title": "40"
          },
          {
            "id": "407396361",
            "title": "41"
          },
          {
            "id": "473680452",
            "title": "42"
          },
          {
            "id": "225078235",
            "title": "43"
          },
          {
            "id": "64797379",
            "title": "44"
          },
          {
            "id": "72380707",
            "title": "37"
          },
          {
            "id": "481222891",
            "title": "45"
          }
        ]
      },
      {
        "id": "1627207",
        "title": "颜色分类",
        "childAttr": [
          {
            "id": "34535608",
            "title": "5222黑色"
          },
          {
            "id": "561912616",
            "title": "5222棕色"
          },
          {
            "id": "67027802",
            "title": "5222黄色"
          },
          {
            "id": "763074192",
            "title": "5221黑色加绒款"
          },
          {
            "id": "769214376",
            "title": "5221棕色加绒款"
          },
          {
            "id": "1543129179",
            "title": "5225黑色增高款"
          }
        ]
      }
    ]`
`stocks: [
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "103189693",
              "title": "38"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 3833
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "103189693",
              "title": "38"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 991
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "103189693",
              "title": "38"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 4631
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "103189693",
              "title": "38"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1340
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "103189693",
              "title": "38"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1863
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "103189693",
              "title": "38"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 422
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "418624880",
              "title": "39"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 337
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "418624880",
              "title": "39"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 3498
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "418624880",
              "title": "39"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 4287
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "418624880",
              "title": "39"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 421
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "418624880",
              "title": "39"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 120
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "418624880",
              "title": "39"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 332
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "229418985",
              "title": "40"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 359
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "229418985",
              "title": "40"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 2503
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "229418985",
              "title": "40"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 3647
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "229418985",
              "title": "40"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 733
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "229418985",
              "title": "40"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 797
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "229418985",
              "title": "40"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 248
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "407396361",
              "title": "41"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 285
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "407396361",
              "title": "41"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 742
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "407396361",
              "title": "41"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 3474
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "407396361",
              "title": "41"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 992
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "407396361",
              "title": "41"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 0
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "407396361",
              "title": "41"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 239
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "473680452",
              "title": "42"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 31
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "473680452",
              "title": "42"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 725
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "473680452",
              "title": "42"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 386
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "473680452",
              "title": "42"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 619
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "473680452",
              "title": "42"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 0
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "473680452",
              "title": "42"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 285
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "225078235",
              "title": "43"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 192
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "225078235",
              "title": "43"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 854
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "225078235",
              "title": "43"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 3876
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "225078235",
              "title": "43"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 58
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "225078235",
              "title": "43"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1019
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "225078235",
              "title": "43"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 107
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "64797379",
              "title": "44"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 194
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "64797379",
              "title": "44"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 648
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "64797379",
              "title": "44"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 4502
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "64797379",
              "title": "44"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 587
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "64797379",
              "title": "44"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1780
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "64797379",
              "title": "44"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 0
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "72380707",
              "title": "37"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 874
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "72380707",
              "title": "37"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 760
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "72380707",
              "title": "37"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 1795
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "72380707",
              "title": "37"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1919
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "72380707",
              "title": "37"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1981
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "72380707",
              "title": "37"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 12
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "34535608",
              "title": "5222黑色"
            }
          }
        ],
        "price": "498.00",
        "count": 402
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "561912616",
              "title": "5222棕色"
            }
          }
        ],
        "price": "498.00",
        "count": 2041
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 741
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "763074192",
              "title": "5221黑色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 1237
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "769214376",
              "title": "5221棕色加绒款"
            }
          }
        ],
        "price": "508.00",
        "count": 401
      },
      {
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "1543129179",
              "title": "5225黑色增高款"
            }
          }
        ],
        "price": "508.00",
        "count": 0
      }
    ]`

**Comment by cnkerry** [comment]
![qq 20170317140311](https://cloud.githubusercontent.com/assets/20836363/24030925/7a045d66-0b1a-11e7-9d09-066960977717.png)
这是效果图。

**Comment by smackgg** [comment]
@cnkerry 我看下

**Comment by cnkerry** [comment]
谢谢！在赶一项目，刚好用上你造的轮子。

**Comment by smackgg** [comment]
@cnkerry 好了，修复了。你拉一下代码

**Comment by cnkerry** [comment]
谢谢！不过又发现了一个问题哦。
尺码45 ，颜色分类 5222黄色，count是741，但是跑起来5222黄色不能选择
![1231232131321321](https://cloud.githubusercontent.com/assets/20836363/24032053/030f16d6-0b21-11e7-9472-c03a33b419a7.png)

`{
        "attribute": [
          {
            "id": "20549",
            "title": "尺码",
            "childAttr": {
              "id": "481222891",
              "title": "45"
            }
          },
          {
            "id": "1627207",
            "title": "颜色分类",
            "childAttr": {
              "id": "67027802",
              "title": "5222黄色"
            }
          }
        ],
        "price": "498.00",
        "count": 741
      }`

**Comment by smackgg** [comment]
稍等，我看下。好久之前写的代码了，有点忘了。。

**Comment by cnkerry** [comment]
@smackgg 好的谢谢 :blush:

**Comment by smackgg** [comment]
@cnkerry 好了。。拉下代码

**Comment by cnkerry** [comment]
😍 OK了，感谢！

**Comment by smackgg** [comment]
@cnkerry 不客气。再有什么问题再告诉我😅  ，这个好久之前写的了，也没人用就没有再维护过。。

**Comment by cnkerry** [comment]
👍 好的，我先用到项目里去，修改一下把sku图片显示出来。
